name: firebase_storage_image
description: A Flutter's ImageProvider for Firebase Cloud Storage.
version: 0.1.0
author: Kohei Asai <me@axross.io>
homepage: https://github.com/axross/firebase_storage_image

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.2.5+1
  firebase_storage: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
