name: firebase_storage_image
description: Flutter's ImageProvider to use images in Firebase Cloud Storage directly for Image, CircleAvatar, ImageIcon, and something like that. Fork of https://github.com/axross/firebase_storage_image. 
version: 0.2.2

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+1
  firebase_storage: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
